# Generated by Django 4.2.3 on 2023-08-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_districts', models.ManyToManyField(blank=True, related_name='child_districts', to='search.district')),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('destination_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_distances', to='search.district')),
                ('source_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_distances', to='search.district')),
            ],
        ),
    ]
